name: Run action with latest version
on:
  pull_request:
  push:
    branches:
      - main
permissions: {}
jobs:
  runner:
    name: Run install-ghalint
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Run action
        uses: ./
      - name: Run ghalint
        run: |
          ghalint --version

