name: Run action with latest version
on:
  pull_request:
  push:
    branches:
      - main
permissions: {}
jobs:
  runner:
    name: Run install-ghalint
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Run action
        uses: ./
      - name: Run ghalint
        run: |
          ghalint --version

